services:
    frontend:
        build: ./frontend
        dockerfile: dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
