import { useState } from "react";
import { FiChevronDown } from "react-icons/fi";

type Difficulty = { label: string; earned: number; total: number };
type Game = { title: string; experience: string; badge: string; progress: number; total: number; difficulties: Difficulty[] };
const difficultyNames = ["Easy", "Medium", "Hard", "Extreme", "El Diablo", "Joker Kebab"];
const games: Game[] = [
  { title: "Cell to Singularity", experience: "EXP 23,847 / 30,000", badge: "Cosmic Pioneer", progress: 40, total: 43, difficulties: difficultyNames.map((label, index) => ({ label, earned: [40, 40, 36, 29, 18, 11][index], total: 43 })) },
  { title: "Hades", experience: "EXP 18,490 / 30,000", badge: "River Styx", progress: 32, total: 49, difficulties: difficultyNames.map((label, index) => ({ label, earned: [32, 30, 25, 17, 10, 6][index], total: 49 })) },
  { title: "Stardew Valley", experience: "EXP 15,720 / 30,000", badge: "Golden Hoe", progress: 28, total: 40, difficulties: difficultyNames.map((label, index) => ({ label, earned: [28, 25, 21, 15, 8, 4][index], total: 40 })) },
  { title: "Hollow Knight", experience: "EXP 10,820 / 30,000", badge: "Dreamer", progress: 22, total: 63, difficulties: difficultyNames.map((label, index) => ({ label, earned: [22, 19, 14, 9, 5, 2][index], total: 63 })) },
];
function GameArt({ title, expanded = false }: { title: string; expanded?: boolean }) { return <div className={`from-brand-tertiary to-surface-overlay border-border flex shrink-0 items-end rounded-lg border bg-linear-to-br p-2 ${expanded ? "h-24 w-36" : "h-20 w-48"}`}><span className="text-font-primary font-serif text-sm leading-none">{title}</span></div>; }
function DifficultyRows({ difficulties }: { difficulties: Difficulty[] }) { return <div className="space-y-2">{difficulties.map(({ label, earned, total }) => { const percent = Math.round((earned / total) * 100); return <div key={label} className="grid grid-cols-[5.5rem_3.25rem_minmax(4rem,1fr)] items-center gap-2 text-xs sm:grid-cols-[7rem_3.5rem_minmax(6rem,1fr)]"><span className="text-font-primary truncate">{label}</span><span className="text-font-muted text-right">{earned} / {total}</span><div className="bg-surface-raised h-2 overflow-hidden rounded-full"><div className="bg-accent-cold h-full rounded-full" style={{ width: `${percent}%` }} /></div></div>; })}</div>; }
function GamesPanel() { const [expandedGame, setExpandedGame] = useState<string | null>(null); return <div className="space-y-3">{games.map((game) => { const isExpanded = expandedGame === game.title; return <article key={game.title} className="border-border bg-surface/75 overflow-hidden rounded-xl border"><button type="button" onClick={() => setExpandedGame(isExpanded ? null : game.title)} aria-expanded={isExpanded} className="hover:bg-effect-glass flex w-full items-center gap-3 p-3 text-left transition-colors sm:gap-4"><GameArt title={game.title} /><div className="min-w-0 flex-1"><h2 className="text-font-primary truncate font-medium">{game.title}</h2><p className="text-font-secondary mt-1 text-sm">{game.experience}</p><div className="mt-3 flex items-center gap-3"><span className="text-font-muted shrink-0 text-xs">Achievement progress</span><div className="bg-surface-raised h-2 flex-1 overflow-hidden rounded-full"><div className="bg-accent-cold h-full rounded-full" style={{ width: `${(game.progress / game.total) * 100}%` }} /></div><span className="text-font-secondary shrink-0 text-xs">{game.progress} of {game.total}</span></div></div><FiChevronDown className={`text-font-secondary h-5 w-5 shrink-0 transition-transform ${isExpanded ? "rotate-180" : ""}`} /></button>{isExpanded && <div className="border-border bg-surface-soft/50 border-t p-4"><DifficultyRows difficulties={game.difficulties} /></div>}</article>; })}</div>; }
export default GamesPanel;
