create table public.game_badges (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  created_at timestamptz not null default now(),
  name text not null,
  description text not null default '',
  additional_note text,
  difficulty text not null,
  tier text not null,
  icon_path text,
  constraint game_badges_name_not_blank check (btrim(name) <> ''),
  constraint game_badges_difficulty_check check (
    difficulty in ('easy', 'medium', 'hard', 'extreme', 'supreme', 'inhuman')
  ),
  constraint game_badges_tier_check check (tier in ('low', 'mid', 'high')),
  constraint game_badges_custom_icon_check check (
    icon_path is null or difficulty = 'inhuman'
  )
);

create unique index game_badges_game_id_name_lower_key
  on public.game_badges (game_id, lower(name));

create index game_badges_game_id_idx
  on public.game_badges (game_id);

-- This table exists on the hosted project from an earlier badge iteration.
-- Keep its existing ownership rows and add the timestamp used by rankings.
create table if not exists public.user_badges (
  user_id uuid not null references auth.users (id) on delete cascade,
  badge_id bigint not null references public.game_badges (id) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_id)
);

alter table public.user_badges
  add column if not exists earned_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.user_badges'::regclass
      and conname = 'user_badges_badge_id_fkey'
  ) then
    alter table public.user_badges
      add constraint user_badges_badge_id_fkey
      foreign key (badge_id)
      references public.game_badges (id)
      on delete cascade;
  end if;
end;
$$;

create index user_badges_badge_id_earned_at_idx
  on public.user_badges (badge_id, earned_at desc);

create index user_badges_user_id_earned_at_idx
  on public.user_badges (user_id, earned_at desc);

alter table public.game_badges enable row level security;
alter table public.user_badges enable row level security;

revoke all on table public.game_badges, public.user_badges from anon, authenticated;
grant select on table public.game_badges, public.user_badges to anon, authenticated;
grant insert, update, delete on table public.game_badges to authenticated;
grant insert, delete on table public.user_badges to authenticated;

create policy "Visible game badges are readable"
on public.game_badges for select
to anon, authenticated
using (
  exists (
    select 1
    from public.games
    where games.id = game_badges.game_id
      and (games.is_published or (select private.is_admin()))
  )
);

create policy "Admins can create game badges"
on public.game_badges for insert
to authenticated
with check ((select private.is_admin()));

create policy "Admins can update game badges"
on public.game_badges for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy "Admins can delete game badges"
on public.game_badges for delete
to authenticated
using ((select private.is_admin()));

create policy "Badge ownership is visible"
on public.user_badges for select
to anon, authenticated
using (true);

create policy "Users can claim their own badges"
on public.user_badges for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can remove their own badge claims"
on public.user_badges for delete
to authenticated
using ((select auth.uid()) = user_id);

create or replace function private.add_badge_game_to_user_library()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_game_library (user_id, game_id)
  select new.user_id, game_id
  from public.game_badges
  where id = new.badge_id
  on conflict (user_id, game_id) do nothing;

  return new;
end;
$$;

revoke all on function private.add_badge_game_to_user_library()
  from public, anon, authenticated;

create trigger add_badge_game_to_user_library
after insert on public.user_badges
for each row execute function private.add_badge_game_to_user_library();
