create schema if not exists private;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'role'
  ) then
    create type public.role as enum ('User', 'Moderator', 'Admin');
  end if;
end;
$$;

alter table public.user_profiles
  add column if not exists role public.role not null default 'User';

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  description text not null default '',
  game_creator text,
  icon_url text,
  thumbnail_url text
);

alter table public.games
  alter column description set default '',
  alter column game_creator drop not null,
  alter column icon_url drop not null,
  alter column thumbnail_url drop not null,
  add column if not exists developer text not null default '',
  add column if not exists publisher text not null default '',
  add column if not exists release_date date,
  add column if not exists genres text[] not null default '{}',
  add column if not exists steam_url text,
  add column if not exists cover_path text,
  add column if not exists cover_position text not null default 'center',
  add column if not exists banner_path text,
  add column if not exists is_published boolean not null default false,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'games'
      and column_name = 'id'
      and is_identity = 'YES'
  ) then
    alter table public.games
      alter column id add generated by default as identity;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.games'::regclass
      and conname = 'games_name_not_blank'
  ) then
    alter table public.games
      add constraint games_name_not_blank check (btrim(name) <> '');
  end if;
end;
$$;

create unique index if not exists games_name_lower_key
  on public.games (lower(name));

create index if not exists games_published_created_at_idx
  on public.games (created_at desc)
  where is_published;

create or replace function private.set_game_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_game_updated_at() from public, anon, authenticated;

drop trigger if exists set_game_updated_at on public.games;
create trigger set_game_updated_at
before update on public.games
for each row execute function private.set_game_updated_at();

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.user_profiles
      where id = (select auth.uid())
        and role = 'Admin'::public.role
    );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

revoke update on table public.user_profiles from authenticated;
grant update (username, bio, country_code, avatar_path, banner_path)
  on table public.user_profiles to authenticated;

insert into public.games (
  id,
  name,
  description,
  game_creator,
  developer,
  publisher,
  release_date,
  genres,
  cover_position,
  is_published
)
values
  (1, 'Fall Guys', 'Fall Guys flings hordes of contestants together online in a mad dash through round after round of escalating chaos until one victor remains. Battle bizarre obstacles, shove through unruly competitors, and overcome the unbending laws of physics.', 'Mediatonic', 'Mediatonic', 'Devolver Digital', '2020-08-04', array['Platform', 'Party'], 'center', true),
  (2, 'Hollow Knight', '', 'Team Cherry', 'Team Cherry', 'Team Cherry', '2017-02-24', array['Action', 'Metroidvania'], 'center', true),
  (3, 'Celeste', '', 'Maddy Makes Games', 'Maddy Makes Games', '', '2018-01-25', array['Platform', 'Indie'], '70% center', true),
  (4, 'Hades', '', 'Supergiant Games', 'Supergiant Games', 'Supergiant Games', '2020-09-17', array['Action', 'Roguelike'], '30% center', true),
  (5, 'Tunic', '', 'Andrew Shouldice', 'Andrew Shouldice', 'Finji', '2022-03-16', array['Action', 'Puzzle'], '20% center', true),
  (6, 'Dead Cells', '', 'Motion Twin', 'Motion Twin', 'Motion Twin', '2018-08-07', array['Action', 'Roguelike'], '75% center', true),
  (7, 'Sea of Stars', '', 'Sabotage Studio', 'Sabotage Studio', 'Sabotage Studio', '2023-08-29', array['RPG', 'Indie'], '45% center', true),
  (8, 'Dave the Diver', '', 'MINTROCKET', 'MINTROCKET', 'Nexon', '2023-06-28', array['Adventure', 'Indie'], '65% center', true),
  (9, 'Ori and the Will of the Wisps', '', 'Moon Studios', 'Moon Studios', 'Xbox Game Studios', '2020-03-11', array['Platform', 'Adventure'], '80% center', true)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  game_creator = excluded.game_creator,
  developer = excluded.developer,
  publisher = excluded.publisher,
  release_date = excluded.release_date,
  genres = excluded.genres,
  cover_position = excluded.cover_position,
  is_published = excluded.is_published;

select setval(
  pg_get_serial_sequence('public.games', 'id'),
  greatest((select coalesce(max(id), 1) from public.games), 1),
  true
);

alter table public.user_game_library
  alter column game_id type bigint using game_id::bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.user_game_library'::regclass
      and conname = 'user_game_library_game_id_fkey'
  ) then
    alter table public.user_game_library
      add constraint user_game_library_game_id_fkey
      foreign key (game_id)
      references public.games (id)
      on delete cascade;
  end if;
end;
$$;

create index if not exists user_game_library_game_id_idx
  on public.user_game_library (game_id);

alter table public.games enable row level security;

revoke all on table public.games from anon, authenticated;
grant select on table public.games to anon, authenticated;
grant insert, update on table public.games to authenticated;

drop policy if exists "Published games are visible" on public.games;
drop policy if exists "Admins can create games" on public.games;
drop policy if exists "Admins can update games" on public.games;

create policy "Published games are visible"
on public.games for select
to anon, authenticated
using (is_published or (select private.is_admin()));

create policy "Admins can create games"
on public.games for insert
to authenticated
with check ((select private.is_admin()));

create policy "Admins can update games"
on public.games for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'game-media',
  'game-media',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can read game media" on storage.objects;
drop policy if exists "Admins can upload game media" on storage.objects;
drop policy if exists "Admins can update game media" on storage.objects;

create policy "Admins can read game media"
on storage.objects for select
to authenticated
using (
  bucket_id = 'game-media'
  and (select private.is_admin())
);

create policy "Admins can upload game media"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'game-media'
  and (storage.foldername(name))[1] = 'games'
  and (select private.is_admin())
);

create policy "Admins can update game media"
on storage.objects for update
to authenticated
using (
  bucket_id = 'game-media'
  and (select private.is_admin())
)
with check (
  bucket_id = 'game-media'
  and (storage.foldername(name))[1] = 'games'
  and (select private.is_admin())
);
