SET local check_function_bodies = off;

ALTER TABLE "public"."user_badges" DROP CONSTRAINT "user_badges_pkey";
ALTER TABLE "public"."user_badges" DROP CONSTRAINT "user_badges_user_id_fkey";
DROP FUNCTION "public"."get_game_leaderboard"(bigint, integer, text);
ALTER TABLE "public"."leaderboard_rankings_settings" ALTER COLUMN "owner_id" DROP DEFAULT;
ALTER TABLE "public"."user_profiles" ALTER COLUMN "username" DROP DEFAULT;

CREATE TABLE "public"."badges" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."badge_id_seq") NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name" text NOT NULL, "game_id" bigint NOT NULL, "unlock_method" text NOT NULL, "icon_url" text NOT NULL,
  CONSTRAINT "badge_pkey" PRIMARY KEY (id)
);
ALTER TABLE "public"."badges" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "message" text NOT NULL, "readed" boolean DEFAULT false, "user_id" uuid NOT NULL,
  CONSTRAINT "notifications_pkey" PRIMARY KEY (id)
);
ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_favorited_games" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(), "game_id" bigint NOT NULL,
  CONSTRAINT "user_favorited_games_pkey" PRIMARY KEY (id), "user_id" uuid NOT NULL DEFAULT auth.uid()
);
ALTER TABLE "public"."user_favorited_games" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_badges" ADD COLUMN "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."users_badges_id_seq") NOT NULL;
ALTER TABLE "public"."user_badges" ADD COLUMN "obtained_at" timestamp WITH time zone NOT NULL DEFAULT now();
ALTER TABLE "public"."user_profiles" ADD COLUMN "created_at" timestamp WITH time zone NOT NULL DEFAULT now();
ALTER TABLE "public"."user_profiles" ADD COLUMN "country" text DEFAULT 'Unknown'::text;
ALTER TABLE "public"."user_profiles" ALTER COLUMN "avatar_path" SET NOT NULL;
ALTER TABLE "public"."user_profiles" ALTER COLUMN "avatar_path" SET DEFAULT 'https://i.ibb.co/GvrzrP4G/USERCHOMIK.webp'::text;
ALTER TABLE "public"."user_profiles" ALTER COLUMN "bio" SET DEFAULT 'No bio provided.'::text;

CREATE TYPE "public"."difficulty" AS ENUM ('Easy', 'Medium', 'Hard', 'Extreme', 'El Diablo', 'Joker Kebab');
ALTER TABLE "public"."badges" ADD COLUMN "difficulty" public.difficulty NOT NULL;
ALTER TYPE "public"."role" ADD VALUE 'Supporter' BEFORE 'Moderator';
