alter table public.game_badges
  add column if not exists display_order integer not null default 0;

with ordered_badges as (
  select
    id,
    row_number() over (
      partition by game_id, difficulty, tier
      order by created_at, id
    ) - 1 as position
  from public.game_badges
)
update public.game_badges
set display_order = ordered_badges.position
from ordered_badges
where game_badges.id = ordered_badges.id;

create index if not exists game_badges_game_difficulty_tier_order_idx
  on public.game_badges (game_id, difficulty, tier, display_order, id);

create table if not exists public.game_badge_creators (
  game_id bigint not null references public.games (id) on delete cascade,
  profile_id uuid not null references public.user_profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (game_id, profile_id)
);

create index if not exists game_badge_creators_profile_id_idx
  on public.game_badge_creators (profile_id);

alter table public.game_badge_creators enable row level security;
revoke all on public.game_badge_creators from anon, authenticated;
grant select on public.game_badge_creators to anon, authenticated;
grant insert, delete on public.game_badge_creators to authenticated;

create policy "Published game badge creators are visible"
on public.game_badge_creators for select
to anon, authenticated
using (
  exists (
    select 1 from public.games
    where games.id = game_badge_creators.game_id
      and (games.is_published or (select private.is_admin()))
  )
);

create policy "Owner manages game badge creators"
on public.game_badge_creators for all
to authenticated
using ((select private.is_leaderboard_owner()))
with check ((select private.is_leaderboard_owner()));

create table if not exists public.game_comments (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  author_id uuid not null references public.user_profiles (id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists game_comments_game_sort_idx
  on public.game_comments (game_id, is_pinned desc, created_at desc);
create unique index if not exists one_pinned_comment_per_game_idx
  on public.game_comments (game_id) where is_pinned;

create table if not exists public.game_comment_likes (
  comment_id bigint not null references public.game_comments (id) on delete cascade,
  profile_id uuid not null references public.user_profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, profile_id)
);

create index if not exists game_comment_likes_comment_id_idx
  on public.game_comment_likes (comment_id);

alter table public.game_comments enable row level security;
alter table public.game_comment_likes enable row level security;
revoke all on public.game_comments, public.game_comment_likes from anon, authenticated;
grant select on public.game_comments, public.game_comment_likes to anon, authenticated;
grant insert, update on public.game_comments to authenticated;
grant insert, delete on public.game_comment_likes to authenticated;

create policy "Published game comments are visible"
on public.game_comments for select
to anon, authenticated
using (
  exists (
    select 1 from public.games
    where games.id = game_comments.game_id
      and (games.is_published or (select private.is_admin()))
  )
);

create policy "Eligible users create comments"
on public.game_comments for insert
to authenticated
with check (
  (select auth.uid()) = author_id
  and exists (
    select 1 from public.user_profiles
    where id = (select auth.uid())
      and role in ('Supporter'::public.role, 'Moderator'::public.role, 'Admin'::public.role, 'Owner'::public.role)
  )
);

create policy "Owner pins game comments"
on public.game_comments for update
to authenticated
using ((select private.is_leaderboard_owner()))
with check ((select private.is_leaderboard_owner()));

create policy "Visible comment likes are readable"
on public.game_comment_likes for select
to anon, authenticated
using (
  exists (
    select 1 from public.game_comments
    join public.games on games.id = game_comments.game_id
    where game_comments.id = game_comment_likes.comment_id
      and (games.is_published or (select private.is_admin()))
  )
);

create policy "Users like comments once"
on public.game_comment_likes for insert
to authenticated
with check ((select auth.uid()) = profile_id);

create policy "Users remove their own likes"
on public.game_comment_likes for delete
to authenticated
using ((select auth.uid()) = profile_id);
